### ISSUE TITLE
Support for RPC v0.2

### ISSUE THREAD

**Issue by archseer** [NethermindEth/caigo#174]
I tried using v0.1 but `starknet-devnet` only implements v0.2. The biggest difference seems to be `starknet_getNonce` and a couple other methods now also take an additional `block_id` parameter.

https://github.com/starkware-libs/starknet-specs/compare/v0.1.0...v0.2.1

**Comment by gregoryguillou** [comment]
Thank you for your feedback and for using caigo! We will move forward with the v0.2 implementation now that devnet has implemented it:
- meanwhile and sorry for that, you can still use caigo with Pathfinder on its `/rpc/v0.1` url
- fix devnet on 0.3.4 instead of the latest release

**Comment by archseer** [comment]
Thanks! Should `rpcv01` be renamed into `rpc` and kept up to date? Since the RPC spec is still pre-1.0 I don't think there's a lot of value in keeping old RPC versions supported since they'll eventually be dropped by all node implementations.

**Comment by gregoryguillou** [comment]
> Thanks! Should `rpcv01` be renamed into `rpc` and kept up to date? Since the RPC spec is still pre-1.0 I don't think there's a lot of value in keeping old RPC versions supported since they'll eventually be dropped by all node implementations.

You are right. I will do it once I am confident v0.2 is okay with devnet and pathfinder.

**Comment by gregoryguillou** [comment]
There is actually a lot to do to finish that issue because all the contract/account deployment has changed and we need all the pieces to havd a proper set of tests. The list below tracks those changes:

- [ ] https://github.com/dontpanicdao/caigo/issues/189
- [ ] https://github.com/dontpanicdao/caigo/issues/188
- [ ] https://github.com/dontpanicdao/caigo/issues/190
- [ ] https://github.com/dontpanicdao/caigo/issues/191
- [ ] https://github.com/dontpanicdao/caigo/issues/192
- [ ] https://github.com/dontpanicdao/caigo/issues/193
- [ ] https://github.com/dontpanicdao/caigo/issues/194
- [ ] https://github.com/dontpanicdao/caigo/issues/195
