### ISSUE TITLE
Fix InstallCounterContract

### ISSUE THREAD

**Issue by Gabulhas** [NethermindEth/caigo#252]
When Unmarshling the counter contract artifact in the InstallCounterContract function (https://github.com/NethermindEth/starknet.go/blob/ExampleDeployAccount/providers_test.go) it's exiting with the following error `error installing counter contract json: cannot unmarshal number into Go struct field EntryPoint.CONSTRUCTOR.offset of type rpcv02.NumAsHex`.

Maybe the artifact is compiled using a version and starknet.go is expecting other version, since it's failing to Unmarshling a number (that is in the artifact counter.json) and it's expecting a an Hex value (type NumAsHex).

**Comment by rianhughes** [comment]
The error is arising because we are using the RPcv02 spec on the main branch at the moment, which basically specifies that the offset should be of type NumAsHex. However, the counter contracts offset is of type int (as it should be in a later spec).

We can either 1) wait until RPCv3 is implemented, or 2) convert the EntryPoint.Constructor.offset to their corresponding hex values

**Comment by Gabulhas** [comment]
Didin't work as offset here (https://github.com/NethermindEth/starknet.go/blob/c70aed75a2ec0fc56ae9ee51cec1e6089a1b7974/rpc/types_contract.go#L145) is also an offset yet it's a int64 insteead of a number.

So which one should it be? Also, should we convert the contracts to a later version of cairo?
