### ISSUE TITLE
Update errors

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/caigo#408]
- [x] Addition of `data` to CONTRACT_ERROR
- [x] Update `traceBlockTransaction` error (this is being solved as part of https://github.com/NethermindEth/starknet.go/issues/427 issue)

**Comment by rianhughes** [comment]
I don't think we need to add a data field for CONTRACT_ERROR. The client will populate it, and it should automatically be stored in the "data" field of RPCError when we receive it.

**Comment by cicr99** [comment]
I believe we need to handle CONTRACT_ERROR the same way we do `ErrNoTraceAvailable` and `ErrUnexpectedError` which also may contain a data field, else you won't be able to do the comparison between the error object that is received and the rpc error in methods such as `EstimateMessageFee` for example

**Comment by joshklop** [comment]
> I believe we need to handle CONTRACT_ERROR the same way we do ErrNoTraceAvailable and ErrUnexpectedError which also may contain a data field

Based on my understanding of the project, I think this makes sense. However, I think there may be one problem with the way it is currently done:

It appears that for `ErrNoTraceAvailable` and `ErrUnexpectedError` the global error variable [is mutated](https://github.com/NethermindEth/starknet.go/blob/e31b591d674f7e8cf6d0c89d1615b520ee3ceb63/rpc/errors.go#L71-L72) instead of being copied. To avoid data races, we should instead copy the value like `rpcErr := *ErrNoTraceAvailable`.
