### ISSUE TITLE
How to verify signature made with Starknet.js?

### ISSUE THREAD

**Issue by bastienfaivre** [NethermindEth/caigo#527]
Hi everyone,

I want to verify a Starknet signature made with starknet.js. More specifically, the signature is made using the function [`signMessage`](https://www.starknetjs.com/docs/API/classes/SignerInterface#signmessage). Therefore, I have access to:

- the signer address (through `starknet.account.address`),
- the message of type [`TypedData`](https://www.starknetjs.com/docs/api/interfaces/types.typeddata/),
- and the resulting `r` and `s` of type bigint from the signature.

Now, with starknet.go, the only provided method to verify a signature is:
```go
func (sc StarkCurve) Verify(msgHash, r, s, pubX, pubY *big.Int) bool
```
My question is then: given the values I have (as listed above), how do I obtain the parameters `msgHash`, `pubX`, and `pubY`?

A more general question would also be: how are the curve coordinates of a public key obtained? And how is the public key obtained from the address?

Thank you for your help!

**Comment by KillerJi** [comment]
Hey You can refer to this link：https://www.starknetjs.com/docs/guides/signature/

**Comment by bastienfaivre** [comment]
Thanks for the answer @KillerJi. Unfortunately, I think you did not understand my question; I want to verify the signature using starknet.go, not with starknet.js (as the link you mentioned refers to). Moreover, the function signature is not the same for the Go and JS implementations, which is why I am explicitly asking how to get the necessary arguments for the Go function `Verify(...)` from the JS variables I have (you can assume that these will be sent to a Go program using JSON).

**Comment by KillerJi** [comment]
> Thanks for the answer @KillerJi. Unfortunately, I think you did not understand my question; I want to verify the signature using starknet.go, not with starknet.js (as the link you mentioned refers to). Moreover, the function signature is not the same for the Go and JS implementations, which is why I am explicitly asking how to get the necessary arguments for the Go function `Verify(...)` from the JS variables I have (you can assume that these will be sent to a Go program using JSON).

Of course I know. I have written it in go before. The idea is the same. You can refer to the code inside and implement it using go.

**Comment by KamyarTaher** [comment]
Hello @KillerJi ! Which code do you refer to ? I'm stuck with this. I have the Starknet wallet account, but no way to get the public key.

**Comment by thiagodeev** [comment]
Hi @BastienFaivre. Sorry for the delay.

1. How can you get `msgHash`, `pubX`, and `pubY` values to pass on the `curve.Curve.Verify` function on starknet-go?
This is related to what @KillerJi says because as you are working with starknet.js you should have read their documentation about how to get those values.  'msgHash', 'pubX', and 'pubY' are general concepts related to cryptography and not exclusive to starknet.go, and as you want to verify a signature made from starknet.js you should have searched or asked to them how to get those values from your code.
But, to help you, I made a Typescript gist using the starknet.js lib (lot of it taken from the link provided by @KillerJi) to show you how to get those values, and how to place them in the starknet.go code:

    https://gist.github.com/thiagodeev/2b9db1f155c5e07367ad16615936a77a (@KamyarTaher, this might be of your interest)

2. How are the curve coordinates of a public key obtained? And how is the public key obtained from the address?
This is deeply related to cryptography so I can't help a lot with this. This is implemented in the 'curve' package of starknet.go, take a look at it. Also, this link will help you to learn more about elliptic-curve https://paulmillr.com/posts/noble-secp256k1-fast-ecc/.

If this helped you, please close the issue.

**Comment by bastienfaivre** [comment]
Hi @thiagodeev, thank you for the helpers. I've done further research and written a guide about signatures on Starknet: [https://dev.to/bastienfaivre/a-guide-on-starknet-signatures-a3m](https://dev.to/bastienfaivre/a-guide-on-starknet-signatures-a3m). I hope it will help other people.

I also deployed a live signature playground: [https://signatures.felts.xyz/](https://signatures.felts.xyz/)
